const { streamGenerate } = require("./openrouter.service");
const { requireString } = require("../utils/validation");
const { logger } = require("../utils/logger");

const TEXT_FILE_EXTENSIONS = new Set([
  ".gd",
  ".gdshader",
  ".shader",
  ".tscn",
  ".tres",
  ".godot",
  ".cfg",
  ".ini",
  ".import",
  ".gdextension",
  ".json",
  ".md",
  ".txt",
  ".yml",
  ".yaml",
  ".cs",
]);

const normalizePath = (filePath = "") =>
  String(filePath).replace(/\\/g, "/").replace(/^\/+/, "");

const getExtension = (filePath = "") => {
  const normalized = normalizePath(filePath).toLowerCase();
  const index = normalized.lastIndexOf(".");
  return index === -1 ? "" : normalized.slice(index);
};

const sanitizeProjectName = (name = "") => {
  const cleaned = String(name)
    .replace(/[^a-zA-Z0-9 _-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();

  return cleaned || "Generated Godot Project";
};

const slugProjectName = (prompt = "") => {
  const words = String(prompt)
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, " ")
    .split(/\s+/)
    .filter((word) => word && !["build", "make", "create", "a", "an", "the", "game"].includes(word))
    .slice(0, 4);

  if (!words.length) return "Generated Godot Project";
  return words.map((word) => word[0].toUpperCase() + word.slice(1)).join(" ");
};

const toJsonText = (raw = "") => {
  const fence = raw.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const candidate = (fence ? fence[1] : raw).trim();
  const firstBrace = candidate.indexOf("{");
  const lastBrace = candidate.lastIndexOf("}");

  if (firstBrace === -1 || lastBrace === -1 || lastBrace <= firstBrace) {
    return candidate;
  }

  return candidate.slice(firstBrace, lastBrace + 1);
};

const parseManifest = (raw = "") => JSON.parse(toJsonText(raw));

const isValidGeneratedFilePath = (filePath = "") => {
  const normalized = normalizePath(filePath);
  if (!normalized || normalized.startsWith(".") || normalized.includes("../")) return false;
  return TEXT_FILE_EXTENSIONS.has(getExtension(normalized));
};

const makeProjectGodot = ({ projectName, mainScene }) => `; Engine configuration file.
; Generated by Godot Assistant.
config_version=5

[application]

config/name="${projectName.replace(/"/g, "'")}"
run/main_scene="res://${mainScene}"
config/features=PackedStringArray("4.2")

[rendering]

renderer/rendering_method="gl_compatibility"
`;

const makeMainScene = () => `[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/Main.gd" id="1_main"]

[node name="Main" type="Node2D"]
script = ExtResource("1_main")
`;

const makeMainScript = ({ prompt, assetPaths }) => {
  const assets = JSON.stringify(assetPaths, null, 2);
  return `extends Node2D

const PlayerScript := preload("res://scripts/Player.gd")
const ProjectileScript := preload("res://scripts/Projectile.gd")
const EnemyScript := preload("res://scripts/Enemy.gd")
const IMPORTED_ASSETS := ${assets}

var player: Node2D
var projectiles: Array[Node2D] = []
var enemies: Array[Node2D] = []
var score := 0
var spawn_timer := 0.0
var banner: Label

func _ready() -> void:
\trandomize()
\tbanner = Label.new()
\tbanner.position = Vector2(18, 14)
\tbanner.text = "Generated prototype: ${prompt.replace(/"/g, "'").slice(0, 90)}\\nMove WASD/Arrows. Shoot with mouse or Space."
\tadd_child(banner)
\tplayer = PlayerScript.new()
\tplayer.position = get_viewport_rect().size * 0.5
\tplayer.shoot_requested.connect(_on_player_shoot_requested)
\tadd_child(player)
\tfor index in range(5):
\t\t_spawn_enemy()
\t_create_asset_preview()

func _process(delta: float) -> void:
\tspawn_timer -= delta
\tif spawn_timer <= 0.0:
\t\tspawn_timer = max(0.35, 1.4 - float(score) * 0.02)
\t\t_spawn_enemy()
\t_update_projectiles(delta)
\t_update_enemies(delta)
\tbanner.text = "Score: %s\\nMove WASD/Arrows. Shoot with mouse or Space." % score

func _on_player_shoot_requested(origin: Vector2, direction: Vector2) -> void:
\tvar projectile := ProjectileScript.new()
\tprojectile.position = origin
\tprojectile.direction = direction.normalized()
\tprojectiles.append(projectile)
\tadd_child(projectile)

func _spawn_enemy() -> void:
\tvar viewport_size := get_viewport_rect().size
\tvar enemy := EnemyScript.new()
\tvar side := randi() % 4
\tif side == 0:
\t\tenemy.position = Vector2(randf_range(0.0, viewport_size.x), -40.0)
\telif side == 1:
\t\tenemy.position = Vector2(viewport_size.x + 40.0, randf_range(0.0, viewport_size.y))
\telif side == 2:
\t\tenemy.position = Vector2(randf_range(0.0, viewport_size.x), viewport_size.y + 40.0)
\telse:
\t\tenemy.position = Vector2(-40.0, randf_range(0.0, viewport_size.y))
\tenemies.append(enemy)
\tadd_child(enemy)

func _update_projectiles(delta: float) -> void:
\tvar viewport := Rect2(Vector2.ZERO, get_viewport_rect().size).grow(120.0)
\tfor projectile in projectiles.duplicate():
\t\tprojectile.tick(delta)
\t\tif not viewport.has_point(projectile.position):
\t\t\tprojectiles.erase(projectile)
\t\t\tprojectile.queue_free()

func _update_enemies(delta: float) -> void:
\tfor enemy in enemies.duplicate():
\t\tenemy.tick(delta, player.position)
\t\tif enemy.position.distance_to(player.position) < enemy.radius + 18.0:
\t\t\tscore = max(0, score - 1)
\t\t\tenemies.erase(enemy)
\t\t\tenemy.queue_free()
\t\t\tcontinue
\t\tfor projectile in projectiles.duplicate():
\t\t\tif enemy.position.distance_to(projectile.position) < enemy.radius + projectile.radius:
\t\t\t\tscore += 1
\t\t\t\tenemies.erase(enemy)
\t\t\t\tprojectiles.erase(projectile)
\t\t\t\tenemy.queue_free()
\t\t\t\tprojectile.queue_free()
\t\t\t\tbreak

func _create_asset_preview() -> void:
\tvar x := 18.0
\tfor asset_path in IMPORTED_ASSETS:
\t\tvar texture := load(asset_path)
\t\tif texture is Texture2D:
\t\t\tvar sprite := Sprite2D.new()
\t\t\tsprite.texture = texture
\t\t\tsprite.position = Vector2(x, 112.0)
\t\t\tsprite.scale = Vector2.ONE * min(48.0 / max(texture.get_width(), 1), 48.0 / max(texture.get_height(), 1))
\t\t\tadd_child(sprite)
\t\t\tx += 58.0
`;
};

const fallbackFiles = ({ projectName, mainScene, prompt, assetPaths }) => [
  {
    path: "project.godot",
    content: makeProjectGodot({ projectName, mainScene }),
  },
  {
    path: "scenes/Main.tscn",
    content: makeMainScene(),
  },
  {
    path: "scripts/Main.gd",
    content: makeMainScript({ prompt, assetPaths }),
  },
  {
    path: "scripts/Player.gd",
    content: `extends Node2D

signal shoot_requested(origin: Vector2, direction: Vector2)

@export var speed := 380.0
var shoot_cooldown := 0.0
var facing := Vector2.RIGHT

func _process(delta: float) -> void:
\tshoot_cooldown = max(0.0, shoot_cooldown - delta)
\tvar direction := Vector2.ZERO
\tif Input.is_key_pressed(KEY_A) or Input.is_key_pressed(KEY_LEFT):
\t\tdirection.x -= 1.0
\tif Input.is_key_pressed(KEY_D) or Input.is_key_pressed(KEY_RIGHT):
\t\tdirection.x += 1.0
\tif Input.is_key_pressed(KEY_W) or Input.is_key_pressed(KEY_UP):
\t\tdirection.y -= 1.0
\tif Input.is_key_pressed(KEY_S) or Input.is_key_pressed(KEY_DOWN):
\t\tdirection.y += 1.0
\tif direction.length() > 0.0:
\t\tposition += direction.normalized() * speed * delta
\tvar mouse_direction := global_position.direction_to(get_global_mouse_position())
\tif mouse_direction.length() > 0.0:
\t\tfacing = mouse_direction
\tif (Input.is_mouse_button_pressed(MOUSE_BUTTON_LEFT) or Input.is_key_pressed(KEY_SPACE)) and shoot_cooldown <= 0.0:
\t\tshoot_cooldown = 0.16
\t\tshoot_requested.emit(global_position + facing * 24.0, facing)
\tqueue_redraw()

func _draw() -> void:
\tdraw_circle(Vector2.ZERO, 18.0, Color(0.25, 0.85, 0.7))
\tdraw_line(Vector2.ZERO, facing.normalized() * 30.0, Color.WHITE, 4.0)
`,
  },
  {
    path: "scripts/Projectile.gd",
    content: `extends Node2D

@export var speed := 760.0
@export var radius := 6.0
var direction := Vector2.RIGHT

func tick(delta: float) -> void:
\tposition += direction.normalized() * speed * delta
\tqueue_redraw()

func _draw() -> void:
\tdraw_circle(Vector2.ZERO, radius, Color(1.0, 0.9, 0.35))
`,
  },
  {
    path: "scripts/Enemy.gd",
    content: `extends Node2D

@export var speed := 120.0
@export var radius := 18.0

func tick(delta: float, target: Vector2) -> void:
\tvar direction := position.direction_to(target)
\tposition += direction * speed * delta
\tqueue_redraw()

func _draw() -> void:
\tdraw_circle(Vector2.ZERO, radius, Color(0.95, 0.28, 0.34))
\tdraw_circle(Vector2.ZERO, radius * 0.45, Color(0.25, 0.04, 0.08))
`,
  },
  {
    path: "README.md",
    content: `# ${projectName}

Generated by Godot Assistant from this prompt:

> ${prompt}

Open this folder in Godot 4.x and run the main scene.

Imported assets are copied to \`assets/imported\`. The generated prototype lists and previews image assets automatically.
`,
  },
];

const createFallbackManifest = ({ prompt, assets }) => {
  const projectName = sanitizeProjectName(slugProjectName(prompt));
  const assetPaths = assets.map((asset) => asset.destinationPath).filter(Boolean);
  const mainScene = "scenes/Main.tscn";

  return {
    projectName,
    summary: "Generated fallback Godot shooter prototype.",
    mainScene,
    files: fallbackFiles({ projectName, mainScene, prompt, assetPaths }),
    notes: [
      "The AI response could not be parsed as a project manifest, so Godot Assistant generated a runnable fallback prototype.",
    ],
  };
};

const buildManifestPrompt = ({ prompt, assets }) => {
  const assetList = assets.length
    ? assets
        .map(
          (asset) =>
            `- ${asset.name} (${asset.extension || "asset"}, ${asset.size || 0} bytes) -> res://${asset.destinationPath}`
        )
        .join("\n")
    : "- No user assets were provided. Build a complete prototype with code-drawn placeholders.";

  return `
You are a senior Godot 4 engineer generating complete importable Godot projects.

Return ONLY valid JSON. No Markdown. No commentary.

Required JSON shape:
{
  "projectName": "Short Game Name",
  "summary": "One sentence summary",
  "mainScene": "scenes/Main.tscn",
  "files": [
    { "path": "project.godot", "content": "complete file contents" },
    { "path": "scenes/Main.tscn", "content": "complete file contents" },
    { "path": "scripts/Main.gd", "content": "complete file contents" }
  ],
  "notes": ["short implementation note"]
}

Rules:
- Generate a small but complete Godot 4.x project that can be opened by importing the generated folder in Godot.
- Include project.godot, one main .tscn scene, and all scripts needed to run.
- Prefer GDScript and code-created gameplay objects over fragile scene dependencies.
- Use typed GDScript where natural.
- Use the provided assets by referencing their res:// paths when useful. Do not embed binary data or base64.
- File paths must be relative and use only project.godot, scenes/, scripts/, resources/, data/, or README.md.
- Keep the project focused enough for free OpenRouter models: at most 12 files, each complete.
- Avoid placeholders like "TODO" or "implement later".
- The result must be playable with keyboard/mouse immediately.

User project request:
${prompt}

Available copied assets:
${assetList}
`;
};

const normalizeManifest = ({ manifest, prompt, assets }) => {
  const projectName = sanitizeProjectName(manifest.projectName || slugProjectName(prompt));
  const mainScene = normalizePath(manifest.mainScene || "scenes/Main.tscn");
  const seen = new Set();
  const files = [];

  (Array.isArray(manifest.files) ? manifest.files : []).forEach((file) => {
    const filePath = normalizePath(file?.path || "");
    if (!isValidGeneratedFilePath(filePath) || seen.has(filePath)) return;
    if (typeof file?.content !== "string") return;

    seen.add(filePath);
    files.push({
      path: filePath,
      content: file.content.replace(/\r\n/g, "\n"),
    });
  });

  const upsertFile = (path, content) => {
    const index = files.findIndex((file) => file.path === path);
    if (index === -1) {
      files.unshift({ path, content });
    } else {
      files[index] = { path, content };
    }
  };

  upsertFile("project.godot", makeProjectGodot({ projectName, mainScene }));

  if (!files.some((file) => file.path === mainScene)) {
    files.push({ path: mainScene, content: makeMainScene() });
  }

  if (!files.some((file) => file.path === "scripts/Main.gd")) {
    files.push({
      path: "scripts/Main.gd",
      content: makeMainScript({
        prompt,
        assetPaths: assets.map((asset) => asset.destinationPath).filter(Boolean),
      }),
    });
  }

  return {
    projectName,
    summary: String(manifest.summary || "Generated Godot project."),
    mainScene,
    files: files.slice(0, 16),
    notes: Array.isArray(manifest.notes) ? manifest.notes.map(String).slice(0, 8) : [],
  };
};

const generateProjectManifest = async ({ prompt, assets = [] }) => {
  const validPrompt = requireString(prompt, "prompt");
  const normalizedAssets = Array.isArray(assets)
    ? assets
        .map((asset) => ({
          name: String(asset?.name || "").trim(),
          extension: String(asset?.extension || "").trim(),
          size: Number(asset?.size || 0),
          destinationPath: normalizePath(asset?.destinationPath || ""),
        }))
        .filter((asset) => asset.name && asset.destinationPath)
        .slice(0, 40)
    : [];

  let output = "";
  let model = "";

  try {
    const result = await streamGenerate({
      prompt: buildManifestPrompt({
        prompt: validPrompt,
        assets: normalizedAssets,
      }),
      system:
        "You output strict JSON manifests for complete Godot projects. You never output Markdown.",
      onToken: (token) => {
        output += token;
      },
    });

    model = result?.model || "";
    const manifest = parseManifest(output);

    return {
      ...normalizeManifest({
        manifest,
        prompt: validPrompt,
        assets: normalizedAssets,
      }),
      model,
      usedFallback: false,
    };
  } catch (error) {
    if (!output.trim()) {
      throw error;
    }

    logger.warn("Falling back to generated Godot project template", {
      message: error instanceof Error ? error.message : String(error),
      outputPreview: output.slice(0, 240),
    });

    return {
      ...createFallbackManifest({
        prompt: validPrompt,
        assets: normalizedAssets,
      }),
      model,
      usedFallback: true,
    };
  }
};

module.exports = {
  generateProjectManifest,
};
